Review_lab
TarasBeshlei/MobileLabs pull request #2
Opened 2019-09-20 11:35 UTC by TarasBeshlei

2019-09-24 17:30 UTC, Detheroc318 requested changes

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
Коментар стосується DS_Store i xcworkspacedata вони мусять бути в ігнорі

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +//import GoogleSignIn
Якщо воно тобі не потрібно видаляй або став марку //TODO: -

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
Добав final

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +//        GIDSignIn.sharedInstance().clientID = "1053255653450-op9vivg4bpl9458kdkjqmkn2b0hqnnrf.apps.googleusercontent.com"
Якщо втебе є речі які коментуєш давай марк

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +//        GIDSignIn.sharedInstance().clientID = "1053255653450-op9vivg4bpl9458kdkjqmkn2b0hqnnrf.apps.googleusercontent.com"
+ Винеси всі стрінги в інший файл тип Constants і звідти діставай

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +    func applicationWillResignActive(_ application: UIApplication) {
Якщо методи нічого не роблять то вони не потрібні( розумію що автозгенеровані але вони зара тобі не потрібні)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +class ViewController: UIViewController {
добав final

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +class ViewController: UIViewController {
+ поправ неймінг контролера, бо назва контролера має відповідати тому що ти робиш на ньому

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    var fbLoginSuccess = false
Якщо це використовується тільки тут добав private або fileprivate

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Пробіли видаль

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Додай марку тип //MARK: - Properties

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Добав //MARK: - Views або IBOutlets

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    @IBOutlet weak var email: UITextField!
добав private бо ти маєш працювати з UI елементами лише в 1 контролері

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Пробіл)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Старайся роби лише 1 пробіл між
 фун тип 
 
private func bla() {} 

func hello()

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        manager.logIn(permissions: [.publicProfile, .email], viewController: self) { (result) in
Дом завдання, почитати про ARC+MRC, retain cycle і про weak vs unowned, будуть питання напишеш

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +//
Якщо не треба видаляй) або знов марка

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    func validationIndication() {
Як думаєш ти вик цей метод тік в цьому файлі, то воно має бути приватним

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        UIApplication.shared.statusBarStyle = .lightContent
Дивись якщо ти робиш оцю штуку `UIApplication.shared.statusBarStyle = .lightContent` то це треба робити тік в AppDelegate бо вона міняє колір статуса у всій апці + в plist View controller-based status bar appearance втебе є, якщо ти хочеш лише в якомусь конкретному скріні то треба юзати `preferredStatusBarStyle`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        self.button.layer.cornerRadius = 7
Це ти можеш поставити з борди Identity Inspector/ key path далі добавляєш `layer.cornerRadius`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +//    @available(iOS 9.0, *)
Якщо не треба цей код видаляй

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
Питання навіщо ти його перевантажував? Тут ти лише сказав `UIApplication.shared.statusBarStyle = UIStatusBarStyle.lightContent` але до того ти це вже робив, поясни нащо?

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    override func viewDidAppear(_ animated: Bool) {
Поправ пробіли і частіше юзай `guard`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +            performSegue(withIdentifier: "WelcomeSegue", sender: self)
(Це моя думка) Зара з `performSegue` мало працють, частіше всього використовують UINavigationController через якого ти будеш робити такі речі - navigationController.pushViewController(yourVC, animated: true)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +            performSegue(withIdentifier: "WelcomeSegue", sender: self)
+ Якщо ти вже працюєш з ними, розбий скріни по різних Storyboards і просто добав референси на інші борди

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +            performSegue(withIdentifier: "WelcomeSegue", sender: self)
https://stackoverflow.com/questions/34578696/how-to-add-storyboard-reference-in-another-storyboard

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Podfile
> +pod 'GoogleSignIn', '4.4.0'
мож не вказувати версію, вони тобі підтягнуться самі останьої версії, + ти не використовуєш цю лібу взагалі тобто видаль її

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +
Пробіл видаль, старайся мати лише 1 пусту лікію

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    override var preferredStatusBarStyle: UIStatusBarStyle {
Пліз визначся що ти використовуєш `preferredStatusBarStyle` або `UIApplication.shared.statusBarStyle = UIStatusBarStyle.lightContent`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +//
+ Зауваження, старайся все групувати тип публічне зверху а приватне знизу це відноситься до фун(IBAction втебе мають бути там де приватні методи і перед ними)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
Пробіли)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +
винеси цю всю логіку в окремий метод(приватний)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +            guard let strongSelf = self else { return }
чому ти не використовуєш `strongSelf` ???

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                self!.performSegue(withIdentifier: "WelcomeSegue", sender: self)
чому тут ти використовуєш `!` якщо втебе є `[weak self]`, просто буде  `self?.performSegue(withIdentifier: "WelcomeSegue", sender: self)` + різниця між weak i unowned - дз

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                    self?.errorInField.text! = "Wrong email or password, try againg."
`self?.email.text! != "" ` поправ 2 момента, перший це text - Optional і його не треба анрапити за допомогою` ! ` - це антипатерн, використовується не дуж часто, 2 момент це те що там є пропертя isEmpty використай її

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                    self?.errorInField.text! = "Wrong email or password, try againg."
Це поправ в всьому проекті бо ти часто робиш це як прикл(email.text!)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        let manager = LoginManager()
Тут падає проект, при скачувані репи(потрібно глянути вживу і зрозуміти в чому справа)

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +import GoogleSignIn
нащо тобі import GoogleSignIn - ти не працюєш з гугл авторизаціїєю

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +import FacebookLogin
import FacebookCore
import FacebookLogin якщо не помиляюся вони депрікейнуті, і на їх заміну використ FBSDKCoreKit i FBSDKLoginKit

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +import FacebookLogin
https://developers.facebook.com/docs/facebook-login/ios

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/Validation.swift
> +class Validation {
Добав final

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/Validation.swift
> +
+ Добав MARK

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        if (fbLoginSuccess == true)
використай тут `guard`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/Validation.swift
> +    func fieldsSlideDown(inField: UITextField) {
Що до пропусків старайся писати в 1 форматі бо бачиш втебе буває по різному то є пробіл то нема. Код стайли скинув.

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                self!.performSegue(withIdentifier: "WelcomeSegue", sender: self)
біля `performSegue(withIdentifier: "WelcomeSegue", sender: self)` забери self

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        UIView.animate(withDuration: 0.1, delay: 0.0, usingSpringWithDamping: 1, initialSpringVelocity: 0, options: UIView.AnimationOptions.curveEaseIn, animations: {
https://medium.com/mackmobile/avoiding-retain-cycles-in-swift-7b08d50fe3ef

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        UIView.animate(withDuration: 0.1, delay: 0.0, usingSpringWithDamping: 1, initialSpringVelocity: 0, options: UIView.AnimationOptions.curveEaseIn, animations: {
Прочитати і поправити щоб не захоплювати `self`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        self.fbSignOut.layer.cornerRadius = 7
218/219 - винеси в сторіборд

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        self.phone.delegate = self
`self` не треба просто `phone.delegate = self`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        // Do any additional setup after loading the view.
видаль цей або перенеси на верх, як він був згенерований

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
Це делегацький метод винеси його в `extension`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        let characterSet = CharacterSet(charactersIn: string)
Поправ неймінг зміної

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        self.title = "Sign Up"
просто `title = "Sing UP"`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +class SignUpFireBase: UIViewController, UITextFieldDelegate {
Добав final

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    @IBOutlet weak var email: UITextField!
Добав `MARK + private`до UI елементів

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    @IBOutlet weak var password: UITextField!
пиши норма неймінги UI елементів ти не password: UITextField -> passwordField: UITextField, emailError - emailErrorLabel

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    @IBOutlet weak var emailErro: UILabel!
emailErro -> emailError

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                self.performSegue(withIdentifier: "WelcomeSegue", sender: nil)
забери `self`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +        if (email.text! == "" || password.text! == "") {
чекни isEmpty і забери ! - антипатерн

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +            validateField()
нащо викликаєш ту саму фун 2 рази?

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    @IBAction func enterButton(_ sender: Any) {
поправ неймінг функції, також sender втебе -> `UIButton `

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +                self.fbLoginSuccess = true
прочитати статю, бо некст пулл ріджекну комент з статею нижче

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/ViewController.swift
> +    func signInFirebase() {
зроби фун `private `

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func signUpErrorDown() {
Поправ валідацію філдів бо поправді це трохи страшно виглядає. Статю з прикладом кину в тг

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        self.performSegue(withIdentifier: "backToSignIn", sender: self)
видаль `self`

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        if ((email.text! != "" && password.text! != "" && name.text! != "" && phone.text! != "") || (password.text! != "" && name.text! != "" && phone.text! != "") || (name.text! != "" && phone.text!
Вже писав коменти щодо цього, дивись вниз

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    static var nameCopy :String! = nil
воу воу воу. Як я розумію ти переєш цю зміну коли пройдеш авторизацію почитай к передавати дані по segue

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    var slideDownCountPassword :Int! = 0
https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    static var nameCopy :String! = nil
https://stackoverflow.com/questions/26207846/pass-data-through-segue

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +class SignUpFireBase: UIViewController, UITextFieldDelegate {
final добав

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    @IBOutlet weak var signInButton: UIButton!
поправ неймінг UI елементів

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        if ((email.text! != "" && password.text! != "" && name.text! != "" && phone.text! != "") || (password.text! != "" && name.text! != "" && phone.text! != "") || (name.text! != "" && phone.text!
isEmpty і забери ! - антипатерн

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    @IBAction func backToSignIn(_ sender: Any) {
забери self

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        Auth.auth().createUser(withEmail: email.text!, password: password.text!) { authResult, error in
стаття про https://medium.com/mackmobile/avoiding-retain-cycles-in-swift-7b08d50fe3ef

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +                if (self.signUpCount == 1) {
Нащо тут взагалі якись каунтер??

2019-09-24 17:30 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func signUpErrorDown() {
Поправ це бо виглядає дуже багато і навантажено, в тг кину приклад з ray wenderlich

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/SignUpFireBase.swift
> +        if ((email.text! != "" && password.text! != "" && name.text! != "" && phone.text! != "") || (password.text! != "" && name.text! != "" && phone.text! != "") || (name.text! != "" && phone.text!
на isEmpty переправив, але без ! все ж матюкається

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/SignUpFireBase.swift
> +    func signUpErrorDown() {
Статті нема(

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/SignUpFireBase.swift
> +    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
Трошки не вшарив як це зробити:/

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/SignUpFireBase.swift
> +        self.fbSignOut.layer.cornerRadius = 7
З самого початку знав, що воно повинно бути десь в сторіборді, але не допер де іменно, тому й сюди написав

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +import FacebookLogin
Чомусь в мене не хотіло працювати з FBSDK тому використовував старішу версію, через неї доречі в тебе й не взлетів проект, але так як це в завданні не обовязкове то не критично думаю)

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +        let manager = LoginManager()
написав вище, потрібо імпортнути старішу лібу:/

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +                self.performSegue(withIdentifier: "WelcomeSegue", sender: nil)
Без self матюкається

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +            guard let strongSelf = self else { return }
хєрова документація гугла і моя необізнаність в свіфті(

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +                self!.performSegue(withIdentifier: "WelcomeSegue", sender: self)
знову матюкається на те що я забрав self

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +                    self?.errorInField.text! = "Wrong email or password, try againg."
хм, я забираю ! , але воно матюкається на нього і коли нажимаю fix воно його назад повертає:/

2019-09-24 20:18 UTC, TarasBeshlei commented on Mobile/Mobile/ViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
В мене були трабли з тим, можливо забу коди забрати

2019-09-25 07:59 UTC, Detheroc318 requested changes

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +class SignInFirebase: UIViewController {
final добав

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +    @IBOutlet weak var fbButton: UIButton!
Неймінг елементів тож поправ

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +    var nameCop = SignUpFireBase.nameCopy
не правильно почитай як передавати дані через segue або navigationController

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +    @IBAction func button(_ sender: Any) {
Пробіл

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +                self.performSegue(withIdentifier: "signout", sender: nil)
self забери + табуляція

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +        self.signOutButton.layer.cornerRadius = 7
Винеси в борду

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +
використай `guard`

2019-09-25 07:59 UTC, Detheroc318 commented on Mobile/Mobile/SignInFirebase.swift
> +            welcome.text! = "Welcome\(nameCop!)"
не юзай ! їх не треба анрапити бо ти їм вже даєш якесь значення тому вони не зможуть бути nil

2019-09-25 11:21 UTC, Detheroc318 requested changes

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
DS_Store не видаляти а ігнорити треба, бачиш він втебе в ріквесті знову - поправ

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/AppDelegate.swift
> +import FBSDKCoreKit
якщо нічого не робиш з лібами то не треба їх імпортувати

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/LogInScreen.swift
> +    override func viewDidLoad() {
Методи життєвого циклу VC мають бути після UI елементів

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    private var slideDownCountEmail :Int = 0
поправ `private var slideDownCountEmail: Int = 0` так правильно

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
```
//MARK: UITextFieldDelegate
extension SignUpFireBase: UITextFieldDelegate {
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        
        let allowedCharacters = CharacterSet.decimalDigits
        let characterSet = CharacterSet(charactersIn: string)
        return allowedCharacters.isSuperset(of: characterSet)
    }
}

```

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
https://docs.swift.org/swift-book/LanguageGuide/Extensions.html

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
```
.DS_Store
*xcuserdata*
*.xcworkspace/xcshareddata/*.xcscmblueprint
*/*.xcodeproj/xcuserdata/
Pods/
archive/назвапроекту.xcarchive/
Podfile.lock
```

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/LogInScreen.swift
> +class LogInScreen: UIViewController {
добав `final`

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/LogInScreen.swift
> +        UIView.animate(withDuration: 0.1, delay: 0.0, usingSpringWithDamping: 1, initialSpringVelocity: 0, options: UIView.AnimationOptions.curveEaseIn, animations: {
Прочитай статую про клоужери яку кидав + на теорії розкажеш що таке клоужери які є типи і тд :)
https://medium.com/mackmobile/avoiding-retain-cycles-in-swift-7b08d50fe3ef

2019-09-25 11:21 UTC, Detheroc318 commented on Mobile/Mobile/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Добав констрейнти до елементів бо всі поїхали на різних девайсах

2019-09-25 11:48 UTC, Detheroc318 commented on Mobile/Mobile/LogInScreen.swift
> +import FBSDKCoreKit
Нащо тобі тут `FBSDKCoreKit` якщо ти юзаєш ` import FacebookCore  import FacebookLogin`  тиж використувуєш стару лібу

2019-09-25 12:22 UTC, Detheroc318 commented on Mobile/Mobile.xcodeproj/xcshareddata/xcschemes/Mobile.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
Коментра щодо git flow організуй структуру бренчів гіті - мастер/дев/девелопмент(це папка)/назва фічі

2019-09-25 12:22 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +        if ((email.text! != "" && password.text! != "" && name.text! != "" && phone.text! != "") || (password.text! != "" && name.text! != "" && phone.text! != "") || (name.text! != "" && phone.text!
бо text - Optional і його треба анврапнути щоб ти міг писати email.text? на крайній випадок додай дефолтне значення

2019-09-25 12:27 UTC, Detheroc318 commented on Mobile/Mobile/SignUpFireBase.swift
> +    func signUpErrorDown() {
https://www.raywenderlich.com/5765-regular-expressions-tutorial-getting-started

2019-10-30 21:53 UTC, merged